---
title: "Process Data for Shiny App on Object Activity at the Harvard Art Museum"
author: "Hannah Hardenbergh"
date: "October 19, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidyverse)
library(forcats)


```


```{r Clean dataframe}
# Read in the data
rawdata <- read_csv("data.csv")

## We want to look at, in the final shiny app, how often objects from the Modern
#and Contemporary Art galleries (rooms numbered 1120, 1110, 1100) get moved and
#if there is a correlation with the artist's ethnic background or nationality,
#which, in this dataset, can be defined as the variable, "nationality".

# The number of times an object has been moved in a given year is defined as
# "moves_year".

# The number of times an object has been viewed online each year, given to us by
# the dataset that was pulled from the api, is defined as "pageviews_year".

# Note: I am ignoring 2008 values because they are 1) all NA values and I don't have
# the data to replace the NAs with numbers, which 2) makes them a logical
# vector. I use as.numeric() to change this below, but it didn't replace NA's
# with numerical values.

# study center views indicate the number of times an object was requested to be
# viewed in the 4th floor study center at the Fogg museum, so we can count this
# as an instance when an object was viewed in person.

# Important: there is unfortunately no way to discern which type of "move" an
# object undergoes, whether it is from one storage unit to another, or from one
# storage unit to the museum and vice versa. Unfortunately, this may skew
# results for my hypothesis about which types of artworks by different artists
# get viewed in the gallery more often. For the purposes of this project,
# however, I will focus on data analysis, cleaning, and visualization, while in
# addition I will look at loose correlations between the frequency of object
# activity and different artists' works. It is still a compelling data set, as
# you will see in the shiny app descriptions and visualization tools.


# change all logical strings to numerical ones

rawdata %>%
  mutate(moves_2008 = as.numeric(moves_2008),
         conservation_2008 = as.numeric(conservation_2008),
         conservation_2009 = as.numeric(conservation_2009),
         conservation_2010 = as.numeric(conservation_2010),
         conservation_2018 = as.numeric(conservation_2018),
         pageviews_2008 = as.numeric(pageviews_2008),
         studycenterviews_2008 = as.numeric(studycenterviews_2008),
         studycenterviews_2009 = as.numeric(studycenterviews_2009),
         studycenterviews_2010 = as.numeric(studycenterviews_2010),
         edits_2008 = as.numeric(edits_2008),
         uniquepageviews_2008 = as.numeric(uniquepageviews_2008)
         )

  
# start tidying the data. Translate all new NA's into 0's.

activity <- rawdata %>% 
  replace_na(list(moves_2009 = 0,
                  moves_2010 = 0,
                  moves_2011 = 0,
                  moves_2012 = 0,
                  moves_2013 = 0,
                  moves_2014 = 0,
                  moves_2015 = 0,
                  moves_2016 = 0,
                  moves_2017 = 0,
                  moves_2018 = 0,
                  
                  pageviews_2009 = 0,
                  pageviews_2010 = 0,
                  pageviews_2011 = 0,
                  pageviews_2012 = 0,
                  pageviews_2013 = 0,
                  pageviews_2014 = 0,
                  pageviews_2015 = 0,
                  pageviews_2016 = 0,
                  pageviews_2017 = 0,
                  pageviews_2018 = 0,
                  
                  studycenterviews_2009 = 0,
                  studycenterviews_2010 = 0,
                  studycenterviews_2011 = 0,
                  studycenterviews_2012 = 0,
                  studycenterviews_2013 = 0,
                  studycenterviews_2014 = 0,
                  studycenterviews_2015 = 0,
                  studycenterviews_2016 = 0,
                  studycenterviews_2017 = 0,
                  studycenterviews_2018 = 0)) %>% 

  
# Add a variable that sums a total of all the times an object has moved since
# 2009.
  
  mutate(total_moves = 
           moves_2009 + 
           moves_2010 + 
           moves_2011 + 
           moves_2012 +
           moves_2013 + 
           moves_2014 + 
           moves_2015 + 
           moves_2016 + 
           moves_2017 + 
           moves_2018) %>% 

  # add another column for total number of pageviews, referring to number of
  # times an object was visited on the museum's public website on a given day
  # since 2009.
  
  mutate(total_pageviews = 
           pageviews_2009 +
           pageviews_2010 + 
           pageviews_2011 + 
           pageviews_2012 + 
           pageviews_2013 + 
           pageviews_2014 + 
           pageviews_2015 + 
           pageviews_2016 + 
           pageviews_2017 + 
           pageviews_2018) %>% 


# Add a total study center views variable while keeping the yearly pageviews observations
# intact with mutate.

  mutate(total_studycenterviews = 
           studycenterviews_2009 + 
           studycenterviews_2010 + 
           studycenterviews_2011 +
           studycenterviews_2012 + 
           studycenterviews_2013 + 
           studycenterviews_2014 + 
           studycenterviews_2015 + 
           studycenterviews_2016 + 
           studycenterviews_2017 + 
           studycenterviews_2018) %>% 
  
  # to plot artists nationalities more generally, broaden the geographic
  # location with which they identify for user accessibility.

  mutate(personculture = fct_collapse(personculture, 
                                     `Europe` = c("German", "French", "British", "Swiss", "Danish", "Austrian"),
                                     `North America` = c("American", "Cuban", "NA"),
                                     `South America` = c("Argentinian", "Venezuelan", "Colombian", "Brazilian"),
                                     `Asia` = c("Japanese", "Chinese", "Palestinian"),
                                     `Australia` = "Australian",
                                     `Africa` = "African"))


```
  

```{r online views table}

# make a tibble for types of moves, including 2 columns per id: online views and
# in-person views. this will be code for making a table in shiny.

movetypes <- activity %>% 
  select(title,
         personname,
         personculture,
         classification,
         total_moves,
         total_pageviews,
         total_studycenterviews) %>% 
  mutate(inperson_views = 
           total_moves +
           total_studycenterviews) %>% 
  rename(online_views = total_pageviews) %>% 
  slice(1:100)

# Make a table to show how many online views an item has since 2009.

online_table <- movetypes

online_table %>% 
  select(title,
         classification,
         personname,
         personculture,
         online_views) %>% 
  arrange(desc(online_views)) %>% 
  kableExtra::kable(col.names = c("Object Title",
                                  "Artwork Medium",
                                  "Artist",
                                  "Artist's Nationality",
                                  "Total Online Views"))
```

```{r inperson views table}
# Make a table that shows how many in-person views an item has had since 2009 (total study center views + total moves)

inperson_table <- movetypes

inperson_table %>% 
  select(title,
         classification,
         personname,
         personculture,
         inperson_views) %>% 
  arrange(desc(inperson_views)) %>% 
  kableExtra::kable(col.names = c("Object Title",
                                  "Artwork Medium",
                                  "Artist",
                                  "Artist's Nationality",
                                  "Total In-Person Views"))

```

```{r write rds for shiny app}
write_rds(activity, "shiny_data.rds")
```

